Ftemov/Ftemov.MVC/Ftemov.MVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Ftemov.MVC.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ftemov/Ftemov.MVC/Ftemov.MVC/Controllers/SportComplexController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Ftemov.MVC.Data;
using Ftemov.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ftemov.MVC.Models.SportComplexViewModels;

namespace Ftemov.MVC.Controllers
{
    public class SportComplexController : Controller
    {
        private ApplicationDbContext _applicationDbContext;
        public SportComplexController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public IActionResult Index()
        {
            var complexes = _applicationDbContext.Complexes.ToList();
            return View(complexes);
        }

        public IActionResult ComplexProfile(int complexId)
        {
            var complex = _applicationDbContext.Complexes.Include(x => x.Builds).First(x => x.Id == complexId);
            return View(complex);
        }

        public IActionResult Build(int buildId)
        {
            var build = _applicationDbContext.Builds.Include(x => x.SportSections).First(x => x.Id == buildId);
            var sections = _applicationDbContext.SportSections.Include(x => x.SportSectionType).Where(x => build.SportSections.Select(y => y.Id).Contains(x.Id)).ToList();
            BuildViewModel buildViewModel = new BuildViewModel()
            {
                Build = build,
                SportSection = sections
            };

            return View(buildViewModel);
        }

        [HttpPost]
        public ActionResult SetBookig(BuildViewModel model)
        {
            Random r = new Random(DateTime.Now.Second);
            var user = _applicationDbContext.Users.First(x => x.UserName == User.Identity.Name);
            DateTime sTime = new DateTime(model.Date.Year, model.Date.Month, model.Date.Day, model.StaDateTime.Hour, model.StaDateTime.Minute, model.StaDateTime.Second);
            DateTime eTime = new DateTime(model.Date.Year, model.Date.Month, model.Date.Day, model.EndDateTime.Hour, model.EndDateTime.Minute, model.EndDateTime.Second);
            SportSection s = _applicationDbContext.SportSections.First(x => x.Id == model.SectionId);
            Booking booking = new Booking()
            {
                ApplicationUser = user,
                BookingStartingDate = sTime,
                BookingEndingDate = eTime,
                ChangedDate = DateTime.Now,
                Cost = r.Next(100, 5000),
                SportSection = s
            };
            _applicationDbContext.Bookings.Add(booking);
            _applicationDbContext.SaveChanges();
            return RedirectToAction("Index", "User");
        }

        public IActionResult SectionPartial()
        {
            return PartialView();
        }
    }
}

Ftemov/Ftemov.MVC/Ftemov.MVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Ftemov.MVC.Data;
using Ftemov.MVC.Models.SportComplexViewModels;
using Ftemov.MVC.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ftemov.MVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private ApplicationDbContext _applicationDbContext;
        public UserController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public IActionResult Index()
        {
            var user = _applicationDbContext.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            
            var booking = _applicationDbContext.Bookings.Include(x => x.SportSection).Where(x => x.ApplicationUser.Id == user.Id).ToList();
                        
            UserCabinetViewModels userCabinetViewModels = new UserCabinetViewModels()
            {
                ApplicationUser = user,
                Bookings = booking
            };
            return View(userCabinetViewModels);
        }
    }
}

Ftemov/Ftemov.MVC/Ftemov.MVC/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Company Ftemov</h5>
                <p class="grey-text text-lighten-4">I'm student working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="https://www.linkedin.com/in/eduard-ftemov-26820412a">Linkedin</a></li>
                    <li><a class="white-text" href="https://www.instagram.com/edftem/">Instagram</a></li>
                    <li><a class="white-text" href="https://www.facebook.com/ed.ftem">Facebook</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="brown-text text-lighten-3" href="https://www.linkedin.com/in/eduard-ftemov-26820412a">Ftemov Eduard</a>
        </div>
    </div>
</footer>

Ftemov/Ftemov.MVC/Ftemov.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ftemov</title>

    <environment include="Development">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />

        <!-- Compiled and minified CSS -->
    </environment>
</head>
<body>

<nav class="navbar" role="navigation">
    <div class="nav-wrapper container">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="brand-logo" id="logo-container">Ftemov</a>
        @await Html.PartialAsync("_LoginPartial")
        <ul class="right hide-on-med-and-down">
            @if (User.Identity.IsAuthenticated)
            {
                <li><a asp-area="" asp-controller="SportComplex" asp-action="Index">Sport Complexes</a></li>
                <li><a asp-area="" asp-controller="User" asp-action="Index">User cabinet</a></li>
            }
            @if (User.IsInRole("Administrator"))
            {
                <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin panel</a></li>
            }
        </ul>
    </div>
</nav>

<div class="container-fluid" Style="height: 100%">
    <div class="row">
        @RenderBody()
    </div>
    @await Html.PartialAsync("_Footer")
</div>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/materialize/js/materialize.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>